//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI_25024WE {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HMI_25024WE.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btnLogClear {
            get {
                return ResourceManager.GetString("btnLogClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open PDF.
        /// </summary>
        internal static string btnOpenPDF {
            get {
                return ResourceManager.GetString("btnOpenPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string btnReload {
            get {
                return ResourceManager.GetString("btnReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to Marker.
        /// </summary>
        internal static string btnSendtoMarker {
            get {
                return ResourceManager.GetString("btnSendtoMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop marking.
        /// </summary>
        internal static string btnStopMarking {
            get {
                return ResourceManager.GetString("btnStopMarking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string btnTemplateEditor_Add {
            get {
                return ResourceManager.GetString("btnTemplateEditor_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Label.
        /// </summary>
        internal static string btnTemplateEditor_AddNode {
            get {
                return ResourceManager.GetString("btnTemplateEditor_AddNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btnTemplateEditor_Delete {
            get {
                return ResourceManager.GetString("btnTemplateEditor_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Label.
        /// </summary>
        internal static string btnTemplateEditor_DeleteNode {
            get {
                return ResourceManager.GetString("btnTemplateEditor_DeleteNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnTemplateEditor_Edit {
            get {
                return ResourceManager.GetString("btnTemplateEditor_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Labels.
        /// </summary>
        internal static string btnTemplateEditor_ImportNodes {
            get {
                return ResourceManager.GetString("btnTemplateEditor_ImportNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom .
        /// </summary>
        internal static string btnZoom1 {
            get {
                return ResourceManager.GetString("btnZoom1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom all.
        /// </summary>
        internal static string btnZoomAll {
            get {
                return ResourceManager.GetString("btnZoomAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string gbSearch {
            get {
                return ResourceManager.GetString("gbSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels Data.
        /// </summary>
        internal static string gbTemplateEditor_Labels {
            get {
                return ResourceManager.GetString("gbTemplateEditor_Labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Data.
        /// </summary>
        internal static string gbTemplateEditor_TextData {
            get {
                return ResourceManager.GetString("gbTemplateEditor_TextData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Files.
        /// </summary>
        internal static string gbXMLFiles {
            get {
                return ResourceManager.GetString("gbXMLFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auxiliar folder.
        /// </summary>
        internal static string lbAuxFolder {
            get {
                return ResourceManager.GetString("lbAuxFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string lbFilterDgv {
            get {
                return ResourceManager.GetString("lbFilterDgv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Serial.
        /// </summary>
        internal static string lbIPMarker {
            get {
                return ResourceManager.GetString("lbIPMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MESSAGE.
        /// </summary>
        internal static string lbMensajeTitulo {
            get {
                return ResourceManager.GetString("lbMensajeTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity completed.
        /// </summary>
        internal static string lbModAutQuantityCompleted {
            get {
                return ResourceManager.GetString("lbModAutQuantityCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity required.
        /// </summary>
        internal static string lbModAutQuantityRequired {
            get {
                return ResourceManager.GetString("lbModAutQuantityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string lbModAutTemplate {
            get {
                return ResourceManager.GetString("lbModAutTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string lbModeAutDate {
            get {
                return ResourceManager.GetString("lbModeAutDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending serial.
        /// </summary>
        internal static string lbModeAutEndSerial {
            get {
                return ResourceManager.GetString("lbModeAutEndSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        internal static string lbModeAutMaterial {
            get {
                return ResourceManager.GetString("lbModeAutMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF File.
        /// </summary>
        internal static string lbModeAutPDF {
            get {
                return ResourceManager.GetString("lbModeAutPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting serial.
        /// </summary>
        internal static string lbModeAutStarSerial {
            get {
                return ResourceManager.GetString("lbModeAutStarSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAMINED PLATE.
        /// </summary>
        internal static string lbParameterLaminedPlate {
            get {
                return ResourceManager.GetString("lbParameterLaminedPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAINTED PLATE.
        /// </summary>
        internal static string lbParameterPaintedPlate {
            get {
                return ResourceManager.GetString("lbParameterPaintedPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Line Interval.
        /// </summary>
        internal static string lbParametersFillLineInterval {
            get {
                return ResourceManager.GetString("lbParametersFillLineInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser Power.
        /// </summary>
        internal static string lbParametersLaserPower {
            get {
                return ResourceManager.GetString("lbParametersLaserPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse Frecuency.
        /// </summary>
        internal static string lbParametersPulseFrequency {
            get {
                return ResourceManager.GetString("lbParametersPulseFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetition.
        /// </summary>
        internal static string lbParametersRepetition {
            get {
                return ResourceManager.GetString("lbParametersRepetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Speed.
        /// </summary>
        internal static string lbParametersScanSpeed {
            get {
                return ResourceManager.GetString("lbParametersScanSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spot Variable.
        /// </summary>
        internal static string lbParametersSpotVarieable {
            get {
                return ResourceManager.GetString("lbParametersSpotVarieable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARKING PARAMETERS.
        /// </summary>
        internal static string lbParameterstitle {
            get {
                return ResourceManager.GetString("lbParameterstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main folder.
        /// </summary>
        internal static string lbPathFiles {
            get {
                return ResourceManager.GetString("lbPathFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number (For USB).
        /// </summary>
        internal static string lbSerialMarker {
            get {
                return ResourceManager.GetString("lbSerialMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APLICATION SETTINGS.
        /// </summary>
        internal static string lbSettingTitle {
            get {
                return ResourceManager.GetString("lbSettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Char Full Widht.
        /// </summary>
        internal static string lbTemplateEditor_CharFullWidth {
            get {
                return ResourceManager.GetString("lbTemplateEditor_CharFullWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Char Height.
        /// </summary>
        internal static string lbTemplateEditor_CharHeight {
            get {
                return ResourceManager.GetString("lbTemplateEditor_CharHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Char Width.
        /// </summary>
        internal static string lbTemplateEditor_CharWidth {
            get {
                return ResourceManager.GetString("lbTemplateEditor_CharWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string lbTemplateEditor_Height {
            get {
                return ResourceManager.GetString("lbTemplateEditor_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        internal static string lbTemplateEditor_LabelAngle {
            get {
                return ResourceManager.GetString("lbTemplateEditor_LabelAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Name.
        /// </summary>
        internal static string lbTemplateEditor_TemplateName {
            get {
                return ResourceManager.GetString("lbTemplateEditor_TemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        internal static string lbTemplateEditor_Templates {
            get {
                return ResourceManager.GetString("lbTemplateEditor_Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Angle.
        /// </summary>
        internal static string lbTemplateEditor_TextAngle {
            get {
                return ResourceManager.GetString("lbTemplateEditor_TextAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string lbTemplateEditorWidth {
            get {
                return ResourceManager.GetString("lbTemplateEditorWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMPLATE EDITOR.
        /// </summary>
        internal static string lbTemplates_Title {
            get {
                return ResourceManager.GetString("lbTemplates_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string menuExit {
            get {
                return ResourceManager.GetString("menuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string menuLanguage {
            get {
                return ResourceManager.GetString("menuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string menuLanguage_English {
            get {
                return ResourceManager.GetString("menuLanguage_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        internal static string menuLanguage_Portuguese {
            get {
                return ResourceManager.GetString("menuLanguage_Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string menuLanguage_Spanish {
            get {
                return ResourceManager.GetString("menuLanguage_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string menuSetting_About {
            get {
                return ResourceManager.GetString("menuSetting_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string menuSettings {
            get {
                return ResourceManager.GetString("menuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        internal static string menuSettings_AppSettings {
            get {
                return ResourceManager.GetString("menuSettings_AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking Parameters.
        /// </summary>
        internal static string menuSettings_Parameters {
            get {
                return ResourceManager.GetString("menuSettings_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Editor.
        /// </summary>
        internal static string menuSettings_TemplateEditor {
            get {
                return ResourceManager.GetString("menuSettings_TemplateEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Template First.
        /// </summary>
        internal static string mjs_ReloadTemplateFirst {
            get {
                return ResourceManager.GetString("mjs_ReloadTemplateFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic mode.
        /// </summary>
        internal static string msj_AutomaticMode {
            get {
                return ResourceManager.GetString("msj_AutomaticMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        internal static string msj_Cancel {
            get {
                return ResourceManager.GetString("msj_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to close the application?.
        /// </summary>
        internal static string msj_CloseTheApplication {
            get {
                return ResourceManager.GetString("msj_CloseTheApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        internal static string msj_ConnectError {
            get {
                return ResourceManager.GetString("msj_ConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        internal static string msj_Connecting {
            get {
                return ResourceManager.GetString("msj_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfully connected to .
        /// </summary>
        internal static string msj_ConnectOK {
            get {
                return ResourceManager.GetString("msj_ConnectOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert DXF to MHL.
        /// </summary>
        internal static string msj_ConvertDXFtoMHL {
            get {
                return ResourceManager.GetString("msj_ConvertDXFtoMHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting files Please wait.
        /// </summary>
        internal static string msj_ConvertingFilesPleaseWait {
            get {
                return ResourceManager.GetString("msj_ConvertingFilesPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert PDF to DXF.
        /// </summary>
        internal static string msj_ConvertPDFtoDXF {
            get {
                return ResourceManager.GetString("msj_ConvertPDFtoDXF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want delete the template: .
        /// </summary>
        internal static string msj_DeleteTemplate {
            get {
                return ResourceManager.GetString("msj_DeleteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting template.
        /// </summary>
        internal static string msj_DeletingTemplate {
            get {
                return ResourceManager.GetString("msj_DeletingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string msj_Done {
            get {
                return ResourceManager.GetString("msj_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred.
        /// </summary>
        internal static string msj_ErrorOccurred {
            get {
                return ResourceManager.GetString("msj_ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when saving parameters.
        /// </summary>
        internal static string msj_ErrorSaving {
            get {
                return ResourceManager.GetString("msj_ErrorSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists.
        /// </summary>
        internal static string msj_FileAlreadyExists {
            get {
                return ResourceManager.GetString("msj_FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file already exists, Do you want to replace it?.
        /// </summary>
        internal static string msj_FileAlreadyExistsReplaceIt {
            get {
                return ResourceManager.GetString("msj_FileAlreadyExistsReplaceIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found, Try opening the PDF first.
        /// </summary>
        internal static string msj_FileNotFoundTryOpenPDF {
            get {
                return ResourceManager.GetString("msj_FileNotFoundTryOpenPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Valid IP Adress.
        /// </summary>
        internal static string msj_InvalidIP {
            get {
                return ResourceManager.GetString("msj_InvalidIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid XML File.
        /// </summary>
        internal static string msj_InvalidXMLFile {
            get {
                return ResourceManager.GetString("msj_InvalidXMLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP NOT Valid.
        /// </summary>
        internal static string msj_IPNotValid {
            get {
                return ResourceManager.GetString("msj_IPNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Label.
        /// </summary>
        internal static string msj_LoadingLabel {
            get {
                return ResourceManager.GetString("msj_LoadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading parameters.
        /// </summary>
        internal static string msj_LoadingParameters {
            get {
                return ResourceManager.GetString("msj_LoadingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading template.
        /// </summary>
        internal static string msj_LoadingTemplate {
            get {
                return ResourceManager.GetString("msj_LoadingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading mouse coordenates.
        /// </summary>
        internal static string msj_LoadMouseCoordenates {
            get {
                return ResourceManager.GetString("msj_LoadMouseCoordenates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual mode.
        /// </summary>
        internal static string msj_ManualMode {
            get {
                return ResourceManager.GetString("msj_ManualMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Marking Detected.
        /// </summary>
        internal static string msj_MarkingAbort {
            get {
                return ResourceManager.GetString("msj_MarkingAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking process finish.
        /// </summary>
        internal static string msj_MarkingDone {
            get {
                return ResourceManager.GetString("msj_MarkingDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string msj_Message {
            get {
                return ResourceManager.GetString("msj_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Conected.
        /// </summary>
        internal static string msj_NotConnected {
            get {
                return ResourceManager.GetString("msj_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter loading completed.
        /// </summary>
        internal static string msj_ParameterLoadingCompleted {
            get {
                return ResourceManager.GetString("msj_ParameterLoadingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path not find it.
        /// </summary>
        internal static string msj_PathNotFind {
            get {
                return ResourceManager.GetString("msj_PathNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Completed.
        /// </summary>
        internal static string msj_QuantityCompleted {
            get {
                return ResourceManager.GetString("msj_QuantityCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want rename the file?.
        /// </summary>
        internal static string msj_RenameTemplate {
            get {
                return ResourceManager.GetString("msj_RenameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        internal static string msj_Save {
            get {
                return ResourceManager.GetString("msj_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully.
        /// </summary>
        internal static string msj_SavedSuccessfully {
            get {
                return ResourceManager.GetString("msj_SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving DXF File.
        /// </summary>
        internal static string msj_SavingDXF {
            get {
                return ResourceManager.GetString("msj_SavingDXF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending.
        /// </summary>
        internal static string msj_Sending {
            get {
                return ResourceManager.GetString("msj_Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want send it to marker?.
        /// </summary>
        internal static string msj_SendToMarking {
            get {
                return ResourceManager.GetString("msj_SendToMarking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking Plates.
        /// </summary>
        internal static string msj_StartMarking {
            get {
                return ResourceManager.GetString("msj_StartMarking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string msj_Success {
            get {
                return ResourceManager.GetString("msj_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Loaded.
        /// </summary>
        internal static string msj_TemplateLoaded {
            get {
                return ResourceManager.GetString("msj_TemplateLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template without coordinates.
        /// </summary>
        internal static string msj_TemplateWithoutCoordinates {
            get {
                return ResourceManager.GetString("msj_TemplateWithoutCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no template.
        /// </summary>
        internal static string msj_ThereNoTemplate {
            get {
                return ResourceManager.GetString("msj_ThereNoTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected a pdf.
        /// </summary>
        internal static string msj_YouHaveNotSelectedaPDF {
            get {
                return ResourceManager.GetString("msj_YouHaveNotSelectedaPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by folder.
        /// </summary>
        internal static string rbSearchByFolder {
            get {
                return ResourceManager.GetString("rbSearchByFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by string.
        /// </summary>
        internal static string rbSearchByString {
            get {
                return ResourceManager.GetString("rbSearchByString", resourceCulture);
            }
        }
    }
}
