//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI_25024WE.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathFiles {
            get {
                return ((string)(this["PathFiles"]));
            }
            set {
                this["PathFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AuxFolder {
            get {
                return ((string)(this["AuxFolder"]));
            }
            set {
                this["AuxFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public double PaintedPlate_LaserPower {
            get {
                return ((double)(this["PaintedPlate_LaserPower"]));
            }
            set {
                this["PaintedPlate_LaserPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int PaintedPlate_ScanSpeed {
            get {
                return ((int)(this["PaintedPlate_ScanSpeed"]));
            }
            set {
                this["PaintedPlate_ScanSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int PaintedPlate_Frequency {
            get {
                return ((int)(this["PaintedPlate_Frequency"]));
            }
            set {
                this["PaintedPlate_Frequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PaintedPlate_SpotVariable {
            get {
                return ((int)(this["PaintedPlate_SpotVariable"]));
            }
            set {
                this["PaintedPlate_SpotVariable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int PaintedPlate_Repetition {
            get {
                return ((int)(this["PaintedPlate_Repetition"]));
            }
            set {
                this["PaintedPlate_Repetition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double PaintedPlate_FillLineInterval {
            get {
                return ((double)(this["PaintedPlate_FillLineInterval"]));
            }
            set {
                this["PaintedPlate_FillLineInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double LaminatedPlate_LaserPower {
            get {
                return ((double)(this["LaminatedPlate_LaserPower"]));
            }
            set {
                this["LaminatedPlate_LaserPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int LaminatedPlate_ScanSpeed {
            get {
                return ((int)(this["LaminatedPlate_ScanSpeed"]));
            }
            set {
                this["LaminatedPlate_ScanSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int LaminatedPlate_Frequency {
            get {
                return ((int)(this["LaminatedPlate_Frequency"]));
            }
            set {
                this["LaminatedPlate_Frequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LaminatedPlate_SpotVariable {
            get {
                return ((int)(this["LaminatedPlate_SpotVariable"]));
            }
            set {
                this["LaminatedPlate_SpotVariable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int LaminatedPlate_Repetition {
            get {
                return ((int)(this["LaminatedPlate_Repetition"]));
            }
            set {
                this["LaminatedPlate_Repetition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public double LaminatedPlate_FillLineInterval {
            get {
                return ((double)(this["LaminatedPlate_FillLineInterval"]));
            }
            set {
                this["LaminatedPlate_FillLineInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CultureInfo {
            get {
                return ((string)(this["CultureInfo"]));
            }
            set {
                this["CultureInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IP_Marker {
            get {
                return ((string)(this["IP_Marker"]));
            }
            set {
                this["IP_Marker"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsLamined {
            get {
                return ((bool)(this["IsLamined"]));
            }
            set {
                this["IsLamined"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("870251")]
        public int ControllerSerialNo {
            get {
                return ((int)(this["ControllerSerialNo"]));
            }
            set {
                this["ControllerSerialNo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseIPConnection {
            get {
                return ((bool)(this["UseIPConnection"]));
            }
            set {
                this["UseIPConnection"] = value;
            }
        }
    }
}
